// impoty fonst constructor
import { Poppins } from 'next/font/google'

const poppins = Poppins({
  weight : ['400' ,'700'] ,
  subsets :['latin']
})
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ poppins.className} >{children}</body>
    </html>
  )
}
